FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# wantz


Models:<br/>
Product model<br/>
    id - product id<br/>
    title - product title<br/>
    description - product description<br/>
    comments_count - count comments on product<br/>
    price - product price<br/>
    wants - wants count<br/>
    media - array of objects (each object contain path to product image)<br/><br/>
Article:<br/>
    id - product id<br/>
    title - article title<br/>
    description - article description<br/>
    items - array of product objects:<br/>
    media - contain object (object contain path to article background image)):<br/><br/>
FeedCollection:<br/>
    id - product id<br/>
    title - feed collection title<br/>
    description - feed collection description<br/>
    template - type of template to display<br/>
    items - array of objects (object may be product or competition)<br/>
    media - contain object (object contain path to feed collection  background image)):<br/>
Competition:
    id - product id<br/>
    title - feed collection title<br/>
    description - feed collection description<br/>
## Feed [/api/v1/feed]
### Feed [GET]

Return array of object
Objects can be of type : product, article or feed_collection
see models description


+ Parameters
    + start (number) - start from
    + limit (number) - count return

+ Response 200 (application/json)
    {
      "body": [
        {
          "type": "product",
          "object": {
            "id": 5,
            "title": "product-title",
            "description": "product-description",
            "comments_count": 1,
            "price": 60,
            "wants": 36,
            "media": [
              {
                "path": "http://wantz.maxp.ocd/images/test.png"
              },
              {
                "path": "http://wantz.maxp.ocd/images/test.png"
              }
            ]
          }
        },
        {
          "type": "article",
          "object": {
            "id": 59,
            "title": "title",
            "description": "description",
            "items": [
              {
                "type": "product",
                "item": {
                  "id": 60,
                  "title": "product-title",
                  "description": "product-description",
                  "comments_count": 47,
                  "price": 51,
                  "wants": 44,
                  "media": [
                    {
                      "path": "http://wantz.maxp.ocd/images/test.png"
                    },
                    {
                      "path": "http://wantz.maxp.ocd/images/test.png"
                    }
                  ]
                }
              },
              {
                "type": "product",
                "item": {
                  "id": 51,
                  "title": "product-title",
                  "description": "product-description",
                  "comments_count": 56,
                  "price": 69,
                  "wants": 30,
                  "media": [
                    {
                      "path": "http://wantz.maxp.ocd/images/test.png"
                    },
                    {
                      "path": "http://wantz.maxp.ocd/images/test.png"
                    }
                  ]
                }
              }
            ],
            "media": {
              "path": "http://wantz.maxp.ocd/images/test.png"
            }
          }
        },
        {
          "type": "feed_collection",
          "object": {
            "id": 85,
            "title": "feed-collection-title",
            "template": "template-3",
            "items": [
              {
                "type": "product",
                "item": {
                  "id": 4,
                  "title": "product-title",
                  "description": "product-description",
                  "comments_count": 24,
                  "price": 6,
                  "wants": 30,
                  "media": [
                    {
                      "path": "http://wantz.maxp.ocd/images/test.png"
                    },
                    {
                      "path": "http://wantz.maxp.ocd/images/test.png"
                    }
                  ]
                }
              },
              {
                "type": "product",
                "item": {
                  "id": 23,
                  "title": "product-title",
                  "description": "product-description",
                  "comments_count": 84,
                  "price": 72,
                  "wants": 13,
                  "media": [
                    {
                      "path": "http://wantz.maxp.ocd/images/test.png"
                    },
                    {
                      "path": "http://wantz.maxp.ocd/images/test.png"
                    }
                  ]
                }
              },
              {
                "type": "competition",
                "item": {
                  "id": 1,
                  "title": "competition-title",
                  "description": "competition-description"
                }
              }
            ],
            "description": "feed-collection-description",
            "media": {
              "path": "http://wantz.maxp.ocd/images/test.png"
            }
          }
        }
      ],
      "status": 200,
      "duration": {
        "time": 0.14899999999995
      },
      "count": 3,
      "action": "success",
    }