FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# wantz

Polls is a simple API allowing consumers to view polls and vote in them.


## Feed [/api/v1/feed]
### Feed [GET]
+ Parameters
    + start (number) - start from
    + limit (number) - count return

+ Response 200 (application/json)
    [
            {
                type: "product",
                item: {
                    id: "id",
                    title: "title",
                    description: "description",
                    comments_count: "comments_count",
                    price: "price",
                    media: [
                        {
                            path: "path"
                        },
                        {
                            path: "path"
                        },
                    ]
                }
            }
        ]